In [1]:
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential, Model
from keras.layers import Dropout, Flatten, Dense, Input
from keras import applications
from keras.layers import AveragePooling2D, GlobalAveragePooling2D
from keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, EarlyStopping, CSVLogger, TensorBoard, LambdaCallback
from keras.applications.resnet50 import ResNet50, preprocess_input 
from keras.layers import Conv2D, Convolution2D, MaxPooling2D, ZeroPadding2D, BatchNormalization, Activation
from keras.optimizers import SGD
from keras import backend as K
import numpy as np
import pandas as pd
from keras import layers
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from keras.models import load_model
import random
import cv2
from PIL import Image
import os
from keras.utils import to_categorical
from collections import defaultdict
from multiprocessing import Pool
from functools import partial
import multiprocessing
import jpeg4py as jpeg
from io import BytesIO

Using TensorFlow backend.


In [17]:
#parameters
classes = 10
batch_size=100
image_size = 512
train_total = 3500
validation_total = 875

In [3]:
model_resnet = ResNet50(include_top=False, weights = 'imagenet',input_shape=(image_size,image_size,3))

ResourceExhaustedError: OOM when allocating tensor with shape[3,3,512,512]
	 [[Node: res5c_branch2b/kernel/Assign = Assign[T=DT_FLOAT, _class=["loc:@res5c_branch2b/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](res5c_branch2b/kernel, res5c_branch2b/random_uniform)]]

Caused by op 'res5c_branch2b/kernel/Assign', defined at:
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-0ffb744280d6>", line 1, in <module>
    model_resnet = ResNet50(include_top=False, weights = 'imagenet',input_shape=(image_size,image_size,3))
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/keras/applications/resnet50.py", line 236, in ResNet50
    x = identity_block(x, 3, [512, 512, 2048], stage=5, block='c')
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/keras/applications/resnet50.py", line 68, in identity_block
    padding='same', name=conv_name_base + '2b')(x)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/keras/engine/topology.py", line 590, in __call__
    self.build(input_shapes[0])
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/keras/layers/convolutional.py", line 138, in build
    constraint=self.kernel_constraint)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/keras/engine/topology.py", line 414, in add_weight
    constraint=constraint)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 392, in variable
    v = tf.Variable(value, dtype=tf.as_dtype(dtype), name=name)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 213, in __init__
    constraint=constraint)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 346, in _init_from_args
    validate_shape=validate_shape).op
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 276, in assign
    validate_shape=validate_shape)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 57, in assign
    use_locking=use_locking, name=name)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[3,3,512,512]
	 [[Node: res5c_branch2b/kernel/Assign = Assign[T=DT_FLOAT, _class=["loc:@res5c_branch2b/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](res5c_branch2b/kernel, res5c_branch2b/random_uniform)]]


In [ ]:
model_resnet.summary()

In [ ]:
x = model_resnet.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.5)(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.5)(x)
x = BatchNormalization()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)
x = BatchNormalization()(x)
x = Dense(classes, activation='softmax')(x)

In [ ]:
for layer in model_resnet.layers:
    layer.trainable = True

In [ ]:
#for layer in model_incepres.layers[-5:]:
#    layer.trainable = True

In [ ]:
model = Model(inputs=model_resnet.input, outputs=x)
model.summary()

In [5]:
train_datagen = ImageDataGenerator(horizontal_flip=True)
validation_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)
                    

In [18]:
train_generator = train_datagen.flow_from_directory(
                    'train',
                    target_size=(image_size,image_size),
                    batch_size=batch_size,
                    class_mode='categorical',
                    shuffle=True
                    )
validation_generator = validation_datagen.flow_from_directory(
                        'validation',
                        target_size=(image_size,image_size),
                        batch_size=batch_size,
                        class_mode='categorical',
                        shuffle=False)

Found 790600 images belonging to 10 classes.
Found 875 images belonging to 10 classes.


In [19]:
def random_crop(image, crop_size):
    h,w,d = image.shape
    rand_num_h = random.randint(0,h-crop_size)
    rand_num_w = random.randint(0,w-crop_size)
    image_crop = image[rand_num_h:rand_num_h+crop_size,rand_num_w:rand_num_w+crop_size,:]
    return image_crop

In [20]:
def multi_process_train(x,y,imggen):

    current  = multiprocessing.current_process()
    
    image = jpeg.JPEG('train/' + x).decode()
    image = image/1.
    image = imggen.random_transform(image)
    image = preprocess_input(image)
    return image,y

In [21]:
def multi_process_valid(x,y):

    current  = multiprocessing.current_process()
    
    image = jpeg.JPEG('validation/' + x).decode()
    image = image/1.

    image = preprocess_input(image)
    return image,y

In [22]:
def train_gen(train_files, train_classes, batch_size, target_size, imggen):
    min_batch_size = batch_size //10
    train_data = list(zip(train_files, train_classes))
    train_data_dict = defaultdict(list)
    for i in range(len(train_data)):
        train_data_dict[train_data[i][0].split('/')[0]].append(train_data[i])
    
    while(True):
        for i in train_data_dict.keys():
            random.shuffle(train_data_dict[i])
        for start in range(0, len(train_data), min_batch_size):
            #image_crop_list = []
            image_classes_list = []
            image_file_list = []
            for j in train_data_dict.keys():
                end = min(start + min_batch_size, len(train_data_dict[j])) 
    
                for i in range(start,end):
                    image_classes_list.append(train_data_dict[j][i][1])
                    image_file_list.append(train_data_dict[j][i][0])
                    
                #x_batch = [train_data_dict[j][i][0] for i in range(start,end)]
                #for i in x_batch:
                #    image = mpimg.imread('train/' + i)
                    #aug_image_recrop = random_crop(image,512)
                 #   image_crop_list.append(image)
                 #   del image
            
            #if(len(image_classes_list)<30):
            #    break
        
            #image_crop_list = [x/1. for x in image_crop_list]
            #image_crop_list = [imggen.random_transform(x) for x in image_crop_list]
            #image_crop_list = [preprocess_input(x) for x in image_crop_list]
            print(image_file_list)
            print(image_classes_list)
            p = Pool(6)
            image_crop_list = p.starmap(partial(multi_process_train,imggen=imggen),zip(image_file_list,image_classes_list))
            p.close()
            p.join()
            
            x_batch_list = [i[0] for i in image_crop_list]
            y_batch_list = [i[1] for i in image_crop_list]
            x_batch = np.array(x_batch_list, np.float32)
            y_batch = np.array(y_batch_list)         
            
            yield (x_batch, y_batch)

In [23]:
train_crop_generator = train_gen(train_generator.filenames,to_categorical(train_generator.classes),batch_size,image_size,train_datagen) 

In [24]:
xx = next(train_crop_generator)

['Motorola-Nexus-6/89_37684279425_6f33b8950d_o.jpg', 'Motorola-Nexus-6/7_38276648424_93d390e163_o.jpg', 'Motorola-Nexus-6/1_(MotoNex6)140.jpg', 'Motorola-Nexus-6/42_37823855742_3df28d90f1_o.jpg', 'Motorola-Nexus-6/4_(MotoNex6)201.jpg', 'Motorola-Nexus-6/21_(MotoNex6)63.jpg', 'Motorola-Nexus-6/40_36977640301_ae328be117_o.jpg', 'Motorola-Nexus-6/87_(MotoNex6)85.jpg', 'Motorola-Nexus-6/22_37126554783_af1e036c0a_o.jpg', 'Motorola-Nexus-6/38_37056263060_55bedbfc37_o.jpg', 'LG-Nexus-5x/26_22306204999_cbd8cefe47_o.jpg', 'LG-Nexus-5x/95_(LG5x)89.jpg', 'LG-Nexus-5x/51_22305548518_5f9cf51f4e_o.jpg', 'LG-Nexus-5x/98_22305271480_c6480fc9fa_o.jpg', 'LG-Nexus-5x/59_34827215284_f48dc8a64b_o.jpg', 'LG-Nexus-5x/27_(LG5x)89.jpg', 'LG-Nexus-5x/64_21872934813_bc3ff85dea_o.jpg', 'LG-Nexus-5x/(LG5x)230.jpg', 'LG-Nexus-5x/25_22479613452_7ecfd15d71_o.jpg', 'LG-Nexus-5x/25_22505315591_c35a856bd4_o.jpg', 'iPhone-6/64_39434268931_c1d78f6333_o.jpg', 'iPhone-6/71_38533029875_0a09ecd129_o.jpg', 'iPhone-6/76_3853214

In [25]:
xx

(array([[[[ -6.99390030e+01,  -6.67789993e+01,  -6.76800003e+01],
          [ -6.19389992e+01,  -5.87789993e+01,  -5.96800003e+01],
          [ -6.39389992e+01,  -6.07789993e+01,  -6.16800003e+01],
          ..., 
          [  5.06099987e+00,   2.62210007e+01,   3.53199997e+01],
          [  5.06099987e+00,   2.62210007e+01,   3.53199997e+01],
          [  7.06099987e+00,   2.82210007e+01,   3.73199997e+01]],
 
         [[ -7.59390030e+01,  -7.27789993e+01,  -7.36800003e+01],
          [ -6.99390030e+01,  -6.67789993e+01,  -6.76800003e+01],
          [ -7.29390030e+01,  -6.97789993e+01,  -7.06800003e+01],
          ..., 
          [  7.06099987e+00,   2.82210007e+01,   3.73199997e+01],
          [  7.06099987e+00,   2.82210007e+01,   3.73199997e+01],
          [  6.06099987e+00,   2.72210007e+01,   3.63199997e+01]],
 
         [[ -7.69390030e+01,  -7.37789993e+01,  -7.46800003e+01],
          [ -6.69390030e+01,  -6.37789993e+01,  -6.46800003e+01],
          [ -6.79390030e+01,  -6.67789

In [16]:
def valid_gen(valid_files, valid_classes, batch_size, target_size, imggen):

    valid_data = list(zip(valid_files, valid_classes))
    
    while(True):
        
        for start in range(0, len(valid_data), batch_size):
            #image_crop_list = []
            image_classes_list = []
            end = min(start + batch_size, len(valid_data)) 
    
            x_batch = [valid_data[i][0] for i in range(start,end)]
            image_classes_list = [valid_data[i][1] for i in range(start,end)]
            #for index,i in enumerate(x_batch):
                #image = mpimg.imread('validation/' + i)
                #if(len(image.shape)<3):
                #        continue
                #rand_num = random.randint(0,7)
                
                #augmented_image = image_aug_valid(image,rand_num)
                #aug_image_recrop = random_crop(image,224)
                #image_crop_list.append(image)
                #image_classes_list.append(valid_data[start+index][1])
                
                #del image
               # del aug_image_recrop
            
            
            #image_crop_list = [x/1. for x in image_crop_list]
            #image_crop_list = [imggen.random_transform(x) for x in image_crop_list]
            #image_crop_list = [preprocess_input(x) for x in image_crop_list]
            p = Pool(1)
            image_crop_list = p.starmap(multi_process_valid,zip(x_batch,image_classes_list))
            p.close()
            p.join()
            
            x_batch_list = [i[0] for i in image_crop_list]
            y_batch_list = [i[1] for i in image_crop_list]
            x_batch = np.array(x_batch_list, np.float32)
            y_batch = np.array(y_batch_list)                  
            
            yield (x_batch, y_batch)

In [17]:
valid_aug_generator = valid_gen(validation_generator.filenames,to_categorical(validation_generator.classes),batch_size,image_size,validation_datagen) 

In [18]:
model.compile(loss='categorical_crossentropy',
             optimizer=SGD(lr=1e-5),
             metrics=['accuracy'])

In [19]:
from pushbullet import Pushbullet
pb = Pushbullet('o.KiDDDXPuzV4qKbXh4Lywbgw1tK2oFfq1')

In [20]:
pushbullet_callback = LambdaCallback(
    on_epoch_end=lambda epoch, logs: pb.push_note("epoch: "+str(epoch),"train_loss: "+str(logs['loss'])+"    val_loss"+str(logs['val_loss'])))

In [21]:
callbacks = [ModelCheckpoint(filepath='resnet_ext_data_full_moto_x_multi.hdf5', verbose=1, save_best_only=True, save_weights_only=True),
ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, verbose=1),
#EarlyStopping(monitor='val_loss', patience=0, verbose=1),
CSVLogger('./3-metrics_ext_data_4.csv'),
TensorBoard(log_dir='logs_ext_data_moto_x', write_graph=True),
pushbullet_callback]

In [23]:
model.fit_generator(
                    train_crop_generator,
                    steps_per_epoch = int(np.ceil(train_total/batch_size)),
                    epochs=100,
                    validation_data=valid_aug_generator,
                    validation_steps= int(np.ceil(validation_total/batch_size)),
                    verbose=1,
                    callbacks=callbacks)

ResourceExhaustedError: OOM when allocating tensor of shape [1,1,512,2048] and type float
	 [[Node: training/SGD/zeros_180 = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [1,1,512,2048] values: [[[0 0 0]]]...>, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'training/SGD/zeros_180', defined at:
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2827, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-25e4f269a8e8>", line 8, in <module>
    callbacks=callbacks)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/keras/engine/training.py", line 2026, in fit_generator
    self._make_train_function()
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/keras/engine/training.py", line 970, in _make_train_function
    loss=self.total_loss)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/keras/optimizers.py", line 171, in get_updates
    moments = [K.zeros(shape) for shape in shapes]
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/keras/optimizers.py", line 171, in <listcomp>
    moments = [K.zeros(shape) for shape in shapes]
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 689, in zeros
    v = tf.zeros(shape=shape, dtype=tf_dtype, name=name)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1439, in zeros
    output = constant(zero, shape=shape, dtype=dtype, name=name)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
    name=name).outputs[0]
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/janardhan/anaconda3/envs/dl/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor of shape [1,1,512,2048] and type float
	 [[Node: training/SGD/zeros_180 = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [1,1,512,2048] values: [[[0 0 0]]]...>, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]


In [22]:
model.load_weights('resnet_before_aug_LB_86.hdf5')


In [83]:
model.evaluate_generator(valid_aug_generator,int(np.ceil(validation_total/batch_size)))

[0.28084943084578429, 0.92571428069046569]

In [111]:
predictions_valid = model.predict_generator(validation_generator,int(np.ceil(validation_total/batch_size)))
predictions_valid = np.argmax(predictions_valid, axis=1)

In [97]:
np.min(next(train_crop_generator)[0])

-123.68

In [115]:
validation_generator.class_indices

{'HTC-1-M7': 0,
 'LG-Nexus-5x': 1,
 'Motorola-Droid-Maxx': 2,
 'Motorola-Nexus-6': 3,
 'Motorola-X': 4,
 'Samsung-Galaxy-Note3': 5,
 'Samsung-Galaxy-S4': 6,
 'Sony-NEX-7': 7,
 'iPhone-4s': 8,
 'iPhone-6': 9}

In [112]:
true_positive = np.zeros(10)
false_positive = np.zeros(10)
true_negative = np.zeros(10)
false_negative = np.zeros(10)
for i in range(len(predictions_valid)):
    if(predictions_valid[i]==validation_generator.classes[i]):
        true_positive[predictions_valid[i]] = true_positive[predictions_valid[i]] + 1
    else:
        false_positive[predictions_valid[i]] = false_positive[predictions_valid[i]] + 1
        false_negative[validation_generator.classes[i]] = false_negative[validation_generator.classes[i]] +1

In [113]:
print('true_positive')
print(true_positive)
print('false_positive')
print(false_positive)
print('false_negative')
print(false_negative)
print('Total')
print(true_positive+false_negative)


true_positive
[  1.   4.   0.  42.   7.  12.   5.  12.  11.  10.]
false_positive
[   9.    4.    1.  351.    9.   22.    7.    6.   13.   24.]
false_negative
[ 52.  58.  61.   7.  49.  46.  50.  26.  46.  51.]
Total
[ 53.  62.  61.  49.  56.  58.  55.  38.  57.  61.]


In [12]:
#validation accuracy 89%

In [52]:
filenames_list = []
images_list = []
for i in os.listdir('test/temp/'):
    img = Image.open('test/temp/'+i)
    filenames_list.append(i)
    images_list.append(np.array(img, np.float32))
    

In [53]:
images_list = [preprocess_input(x) for x in images_list]

In [54]:
new_array_arr = np.array(images_list)


In [55]:
new_array_arr.shape

(13200, 224, 224, 3)

In [56]:
test_preds = model.predict(new_array_arr)

In [57]:
test_preds[0]

array([ 0.0062907 ,  0.83159941,  0.02058052,  0.02371608,  0.00381423,
        0.03507144,  0.002363  ,  0.06212637,  0.00958897,  0.00484931], dtype=float32)

In [58]:
f = defaultdict(list)
for i,j in enumerate(filenames_list):
    f[j[2:]].append(i)

In [59]:
f

defaultdict(list,
            {'img_30b38ba_manip.tif': [205, 3180, 3858, 4312, 11362],
             'img_694ecf4_unalt.tif': [238, 3202, 5424, 5610, 8084],
             'img_380dab3_manip.tif': [235, 2448, 2715, 4546, 6549],
             'img_470c023_unalt.tif': [920, 1852, 5753, 6237, 9046],
             'img_3428729_manip.tif': [190, 936, 8513, 9132, 12052],
             'img_6e2bd5b_unalt.tif': [1206, 1363, 9208, 10995, 11816],
             'img_6f759f8_manip.tif': [242, 443, 7942, 9229, 9862],
             'img_2369d08_manip.tif': [3096, 5636, 6769, 6816, 11855],
             'img_1ac7c07_unalt.tif': [4, 3023, 3106, 7632, 12287],
             'img_a02b647_unalt.tif': [4048, 4504, 5471, 11384, 12041],
             'img_f75f191_manip.tif': [1554, 5265, 8009, 9036, 9573],
             'img_c3cf6df_unalt.tif': [6412, 7280, 7703, 10282, 12159],
             'img_acce035_unalt.tif': [1357, 1872, 2442, 5068, 5992],
             'img_8b2d44e_manip.tif': [6203, 7946, 8835, 9047, 13170],
  

In [60]:
class_ids = {train_generator.class_indices[x]: x for x in train_generator.class_indices}

In [61]:
result_filenames=[]
predicted_classes=[]
for i in f.keys():
    x = np.mean(test_preds[f[i]],axis=0)
    result_filenames.append(i)
    predicted_classes.append(class_ids[np.argmax(x)])

In [62]:
predicted_classes

['iPhone-6',
 'Motorola-Nexus-6',
 'Motorola-Droid-Maxx',
 'Motorola-Nexus-6',
 'LG-Nexus-5x',
 'Motorola-Droid-Maxx',
 'Samsung-Galaxy-Note3',
 'Motorola-Nexus-6',
 'iPhone-6',
 'Sony-NEX-7',
 'LG-Nexus-5x',
 'LG-Nexus-5x',
 'HTC-1-M7',
 'Sony-NEX-7',
 'HTC-1-M7',
 'Samsung-Galaxy-Note3',
 'LG-Nexus-5x',
 'Motorola-X',
 'Samsung-Galaxy-S4',
 'Motorola-Droid-Maxx',
 'iPhone-6',
 'Samsung-Galaxy-Note3',
 'iPhone-4s',
 'LG-Nexus-5x',
 'iPhone-4s',
 'iPhone-4s',
 'iPhone-6',
 'iPhone-4s',
 'LG-Nexus-5x',
 'Motorola-X',
 'LG-Nexus-5x',
 'Motorola-Nexus-6',
 'Samsung-Galaxy-Note3',
 'Samsung-Galaxy-Note3',
 'Motorola-Droid-Maxx',
 'iPhone-6',
 'HTC-1-M7',
 'Motorola-Droid-Maxx',
 'iPhone-6',
 'Motorola-X',
 'LG-Nexus-5x',
 'Motorola-X',
 'HTC-1-M7',
 'Motorola-Droid-Maxx',
 'iPhone-4s',
 'Motorola-Nexus-6',
 'LG-Nexus-5x',
 'Samsung-Galaxy-S4',
 'Sony-NEX-7',
 'Motorola-Nexus-6',
 'Sony-NEX-7',
 'Samsung-Galaxy-S4',
 'Samsung-Galaxy-Note3',
 'Motorola-Droid-Maxx',
 'Samsung-Galaxy-Note3',
 

In [56]:
#class_ids = {train_generator.class_indices[x]: x for x in train_generator.class_indices}
#predicted_classes = [class_ids[x] for x in np.argmax(test_preds, axis=1)]

In [30]:
for index,i in enumerate(result_filenames):
    if(i.split('_')[-1]=='manip.tif'):
        predicted_classes[index]=''

In [65]:
submission = pd.DataFrame({'fname':result_filenames,'camera':predicted_classes})
submission.to_csv('submission_resnet_v2_ext_data_moto_x.csv', encoding="utf8", index=False)

In [66]:
from IPython.display import FileLink
FileLink('submission_resnet_v2_ext_data_moto_x.csv')

/home/janardhan/camera_model/submission_resnet_v2_ext_data_moto_x.csv